In [1]:
from DataLoader import LoadData_Abalone, LoadData_Banknote

In [2]:
X, Y = LoadData_Banknote()

In [3]:

print(X)
print(Y)
print(X.shape)
print(Y.shape)

[[108.6661   97.1927   99.55301]
 [108.1674   97.5414   98.5379 ]
 [ 97.3617  101.9242  100.10645]
 ...
 [ 86.5414  117.5932   97.2229 ]
 [ 91.6173  112.393    98.7177 ]
 [ 99.34196 102.6842  101.1952 ]]
[0 0 0 ... 1 1 1]
(1372, 3)
(1372,)


In [ ]:
    
X_shifted = np.zeros(X_raw.shape)
for i in range(0,X_raw.shape[1]):
    X_i = X_raw[:,i]
    print(np.amin(X_i))
    min_i = 100 #np.amin(X_i)
    X_shifted_i = X_i + np.absolute(min_i+1)
    X_shifted[:,i] = X_shifted_i

print(X_shifted)